project:
  type: website
  output-dir: docs

website:
  title: "4Firs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Blog
format:
  html:
    theme: flatly
    toc: true
